id: demo
require:
  - mecha.contrib.nesting
data_pack:
  load: "src"
pipeline:
  - mecha
meta:
  nesting:
    generate_execute: >-
      {% if original_location == "demo:foo" -%}
      demo:special_execute_{incr}
      {%- else -%}
      {namespace}:zprivate/{path}nested_execute_{incr}
      {%- endif %}
